name: Build Ultimate GD Toolkit

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-android64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Geode mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: given
          target: Android64
          build-config: Release
          use-lto: true

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: UltimateGDToolbox-Android64
          path: ${{ steps.build.outputs.build-output }}/*.geode
          if-no-files-found: error
